### PR TITLE
Auto build based on python

### PR DESCRIPTION
**Pull request by bgruening**
The former bash script was getting to complicated and hard to read, at least for me ;)
This is a port to python which should give us a little bit more flexibility for the changes coming to bioconda and conda-forge in the next month.

It also adds a test task, and extracts tests from the meta.yaml file.

ping @thriqon

### CODE REVIEW

**Comment by bgruening** [comment]
I think this is working pretty well, I have created 500 containers in the last day :)
@thriqon let me know what you think so we can merge it!

**Comment by thriqon** [comment]
It looks nice, and if it works, thats great :) My only issue is that it uses an out-of-container conda, which shouldn't be neccessary... After all, a containerized build is reproducible ;-)

**Comment by bgruening** [comment]
@thriqon good point. But this is only for getting conda-build as lib. I need this to parse the meta.yaml files. Are you fine with merging now and improving on it later on?

**Comment by thriqon** [comment]
yes, go ahead :+1:

**Comment by bgruening** [comment]
Awesome! Thanks!

**Pull request merged**
