### PR TITLE
Fix up Python code-style.

### PR DESCRIPTION
**Pull request by jmchilton**
- Fix docstrings to be inline with PEP8 and flake8-docstrings recommendations.
- Consistent and Python 3 compatible use of print function.
- Fix various whitespace inconsistencies.

### CODE REVIEW

**Comment by jmchilton** [comment]
Next up for `helper.py`.
- Adding argparse help and such to allow more tailored commands.
- Add CLI option to build a single recipe.
- Use this pattern http://stackoverflow.com/a/19263313 to allow multiple recipes at once.
- Add an empty `__init__.py` file so I can use this as a submodule in planemo (unless you want to publish it to PyPI).

Is that an okay plan for the day or are there any of those changes you wouldn't want?

**Comment by bgruening** [comment]
This sounds awesome. But please take it completely over. No need for a submodule, I can use planemo here - but maybe this should end up in galaxy-lib?

**Comment by thriqon** [comment]
If you want to do a complete overhaul of the `helper.py` please keep in mind that we initially wanted to use a fully-containerized build (at least, as much as possible) to keep the results reproducible.

I'd be very supportive towards a plan that incorporates `planemo` inside a container, though.

**Comment by jmchilton** [comment]
@thriqon I'll keep that in mind - it seems less important than what is insider the resulting containers but I like the dedication to complete reproduciblity. If we care about these issues - should we write some more information in the container - like dump the complete list of conda installed software and versions, the version of conda used, the version of mulled, the command-line arguments, etc.... Maybe into like a `/mulled.json` file?

**Pull request merged**
